name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci_testing
  pull_request:

jobs:
  crlf-check:
    name: crlf-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check CRLF
        uses: erclu/check-crlf@v1
        with:
          path: .
